service: journal-tools-backend

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10

  environment:
    NODE_ENV: production

  iamRoleStatements:
    - Effect: Allow
      Action:
        - es:ESHttpGet
        - es:ESHttpHead
        - es:ESHttpPost
      Resource: ${file(config.json):production.elasticsearch.arn}
    - Effect: Allow
      Action:
        - s3:HeadBucket
      Resource:
        - "*"
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
        - s3:GetObjectAcl
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:ListBucketMultipartUploads
        - s3:ListMultipartUploadParts
        - s3:AbortMultipartUpload
        - s3:DeleteObject
      Resource:
        - arn:aws:s3:::autopull-uploads
        - arn:aws:s3:::autopull-uploads/*
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/AmazonRDSDataFullAccess
    - arn:aws:iam::aws:policy/AmazonSQSFullAccess

package:
  exclude:
    - claudia_deploy.sh
    - claudia.json
    - bin/**
    - cleaning/**
    - data/**
    - node_modules/**/aws-sdk/**
    - src/**
    - venv/**
  include:
    - app.js
    - config.json
    - elasticsearch.js
    - lambda.js
    - models.js
    - sql.js
    - data/abbreviations.json
    - routes/*.js

plugins:
  # - serverless-plugin-include-dependencies

custom:
  includeDependencies:
    always:
      - node_modules/pg/**
      - node_modules/pg-native/**

functions:
  apiServer:
    handler: lambda.handler
    timeout: 15
    events:
      - http: ANY /api/{proxy+}

resources:
  Resources:
    S3ReadRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ApigS3ReadOnly
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - apigateway.amazonaws.com
              Action:
                - sts:AssumeRole
    IndexProxyMethod:
      Type: AWS::ApiGateway::Method
      Properties:
        ResourceId:
          Fn::GetAtt:
            - ApiGatewayRestApi
            - RootResourceId
        RestApiId:
          Ref: ApiGatewayRestApi
        HttpMethod: GET
        AuthorizationType: NONE
        MethodResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Content-Type: true
        Integration:
          Type: AWS
          Credentials:
            Fn::GetAtt:
              - S3ReadRole
              - Arn
          Uri: arn:aws:apigateway:${self:provider.region}:s3:path/pdfapi-static/index.html
          IntegrationHttpMethod: GET
          IntegrationResponses:
            - StatusCode: 200
              ResponseParameters:
                method.response.header.Content-Type: integration.response.header.Content-Type
          PassthroughBehavior: WHEN_NO_MATCH
    ScriptsResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        ParentId:
          Fn::GetAtt:
            - ApiGatewayRestApi
            - RootResourceId
        PathPart: javascripts
        RestApiId:
          Ref: ApiGatewayRestApi
    ScriptsProxyResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        ParentId:
          Ref: ScriptsResource
        PathPart: "{proxy+}"
        RestApiId:
          Ref: ApiGatewayRestApi
    ScriptsProxyMethod:
      Type: AWS::ApiGateway::Method
      Properties:
        ResourceId:
          Ref: ScriptsProxyResource
        RestApiId:
          Ref: ApiGatewayRestApi
        HttpMethod: GET
        AuthorizationType: NONE
        RequestParameters:
          method.request.path.proxy: true
        MethodResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Content-Type: true
        Integration:
          Type: AWS
          Credentials:
            Fn::GetAtt:
              - S3ReadRole
              - Arn
          Uri: arn:aws:apigateway:${self:provider.region}:s3:path/pdfapi-static/javascripts/{key}
          RequestParameters:
            integration.request.path.key: method.request.path.proxy
          IntegrationHttpMethod: GET
          IntegrationResponses:
            - StatusCode: 200
              ResponseParameters:
                method.response.header.Content-Type: integration.response.header.Content-Type
          PassthroughBehavior: WHEN_NO_MATCH
